### ISSUE TITLE
Mismatch between ayah counters 

### ISSUE THREAD

**Issue by aliabd** [abidlabs/tarteel.io#60]
When I created this issue, it said 945 near logo, 952 in about page counter, and 944 in subscribe page

**Comment by abidlabs** [comment]
There still seems to be a discrepancy, because we add 1 to the count value when display it in navbar using `renderCounter()`. Why is that? @bahaa96

**Comment by abidlabs** [comment]
Never mind, I see the reason. I've subtracted one from the counter, so it should be consistent now.
