### ISSUE TITLE
Adding example settings.py file

### ISSUE THREAD

**Issue by mohamedgomran** [abidlabs/tarteel.io#81]
Can you please add an example for settings.py?

**Comment by abidlabs** [comment]
@mohamedgomran thanks for the suggestion, will do.

**Comment by abidlabs** [comment]
For now, check out tarteel.io/docs/example-settings.py.

If you move it into hifz_django/. and rename it as "settings.py," that should be enough to be able to work locally. We're working on a better fix in the near future inshaallah.

**Comment by abidlabs** [comment]
Let me know if you run into any further issues.

**Comment by mohamedgomran** [comment]
@abidlabs Thank you.
