### ISSUE TITLE
Firefox:  navigator.getUserMedia is not a function

### ISSUE THREAD

**Issue by mohamedgomran** [abidlabs/tarteel.io#87]
While trying to start recording on Firefox I get navigator.getUserMedia is not a function.

I believe this is because getUserMedia() is deprecated on Firefox, must use navigator.mediaDevices.getUserMedia().

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia#Browser_compatibility

**Comment by bahaa96** [comment]
Thanks a lot bro for reporting this issue 😍😘. It's fixed now will be in production in few hours.
