### ISSUE TITLE
mobile app issues with next button

### ISSUE THREAD

**Issue by 3bdoelnaggar** [abidlabs/tarteel.io#91]
When i hit next nosing happens

**Comment by bahaa96** [comment]
Could you explain to us how to reproduce this issue ?

**Comment by tifa2UP** [comment]
I've experienced this as well. A little difficult to reproduce, might have to do with the async stuff.

**Comment by bahaa96** [comment]
@3bdoelnaggar Do you mean The green next button ?

**Comment by 3bdoelnaggar** [comment]
Yes

**Comment by bahaa96** [comment]
@3bdoelnaggar If it's fixed now ?
