### ISSUE TITLE
Suggestion: Add description to the about page counter

### ISSUE THREAD

**Issue by tifa2UP** [abidlabs/tarteel.io#93]
![image](https://user-images.githubusercontent.com/11590314/44951435-dc1aeb80-ae18-11e8-92d3-d926519a57c6.png)
 
How about we add Ayas recited under the total number. And below it, we say, "You recited: [number] Ayas"

Also, should we include the total ayas recorded on the landing page (pre-onboarding)? The design could be the same as the navbar design.

**Comment by abidlabs** [comment]
This is fixed on the live website.
